apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: sync-server
  namespace: sync-server
spec:
  fleetName: sync-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 5
      maxReplicas: 10
