apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sync-server

resources:
  - resources/namespace.yaml
  - resources/gameserver.yaml
  - resources/clusterissuer.yaml
  - resources/certificate.yaml
